### ISSUE TITLE
package_omssa_2_1_9 dead link

### ISSUE THREAD

**Issue by machacm** [iracooke/protk-galaxytools#8]
Dear Administrators, 
 
I'm trying to install few proteomics tools to Galaxy server, including Omssa. Unfortunately, the Dropbox link (https://dl.dropboxusercontent.com/u/226794/galaxy/omssa_2.1.9.tar.gz) to the Omssa package 2.1.9 (https://toolshed.g2.bx.psu.edu/repository?user_id=fa94c90217a90d64) is dead. Could I kindly ask you to re-upload the link and/or refresh the Toolshed package?

Thank you.

**Comment by iracooke** [comment]
Thanks for letting me know. 

I've updated the toolshed repository with a new download link.  Hopefully it will work now.

**Comment by machacm** [comment]
Thanks a lot. I can confirm it works smoothly now.
